volumes:
  node_modules:
    driver: local


version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6380:6379"
  app:
    container_name: online-bookstore
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    tty: true
